version: "3.3"

services:
  postgres_db:
    image: postgres:13.3-alpine
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
  web:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres_db
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: