# Generated by Django 3.2.8 on 2021-10-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20211025_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspSystem',
            fields=[
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False, verbose_name='Почта')),
            ],
        ),
    ]
