# Generated by Django 3.2.8 on 2021-10-25 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_espsystem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EspSystem',
            new_name='EspSystemUser',
        ),
    ]
